### ISSUE TITLE
No colouring in html and htm files when HTML LSP-based editor is enabled

### ISSUE THREAD

**Issue by graymatter00** [madskristensen/RainbowBraces#102]
Braces, brackets, etc. are not coloured in **html** and **htm** files when the **HTML LSP-based editor** option is enabled. See screenshots below.

The **HTML LSP-based editor** option...

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/7464fe40-8456-4568-a7c1-e3ae30cc880a)

**html** file with the option **enabled**...

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/c5456453-c014-4859-b3e7-86032792b5a1)

**htm** file with the option **enabled**...

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/cc7643f8-b88b-4a0f-b0d1-2e2c1af45d12)

**html** file with the option **disabled**...

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/f2b9e2a0-eb9a-4a43-b6b1-a211c6ae74f2)

**htm** file with the option **disabled**...

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/cc014a99-3d6b-4a3d-91ea-4d00367f9276)

**Comment by lordfanger** [comment]
Thank you very much, the fix PR is on the fly.

**Comment by lordfanger** [comment]
I'll think about it. The problem is that in HTML colorization is OFF by default so it won't colorize for example `)` in `<span> :) </span>`. But in CSS and JavaScript it is ON by default. I'll have to rework code to be aware of context where the parser is. If inside <style> use CSS rules, if inside <script> use JS rules. And maybe for attributes `style=""` and `onclick=""` also.

If you'll find something else, post it.

**Comment by graymatter00** [comment]
@madskristensen Given the above comments, perhaps this issue should be reopened.
